name: Docker Build Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build React App
        run: |
          npm ci --legacy-peer-deps
          CI=false
          REACT_APP_BACKEND_SERVER="http://labconnect.cs.rpi.edu:9000"
          npm run build
      - name: "Build Docker Image"
        run: |
          docker build .
