name: Docker Build Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build React App
        run: |
          npm ci --legacy-peer-deps
          CI=false
          npm run build
      - name: "Build Docker Image"
        run: |
          docker build .
