name: Docker Build Test

on:
  pull_request:
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "package.json"
      - "package-lock.json"
      - "Dockerfile"
      - ".dockerignore"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "Build Docker Image"
        run: |
          docker build -t labconnect-frontend .

      - name: "Run Docker Container"
        run: |
          docker run -d --name labconnect-frontend-container labconnect-frontend
          sleep 30
          docker logs labconnect-frontend-container
          docker stop labconnect-frontend-container
      
      - name: "Check for Container Exit Code"
        id: check_exit_code
        run: |
          docker inspect labconnect-frontend-container --format='{{.State.ExitCode}}'
          docker rm labconnect-frontend-container

      - name: "Fail if Container Fails"
        if: steps.check_exit_code.outputs.exit_code != '0'
        run: exit 1