name: Docker Build Test

on:
  pull_request:
    paths:
      - "**.js"
      - "**.jsx"
      - "**.ts"
      - "**.tsx"
      - "package.json"
      - "package-lock.json"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build React App
        run: |
          npm ci --legacy-peer-deps
          CI=false
          REACT_APP_BACKEND_SERVER="https://api.labconnect.cs.rpi.edu"
          npm run build

      - name: "Build Docker Image"
        run: |
          docker build -t labconnect-frontend .

      - name: "Run Docker Container"
        run: |
          docker run -d --name labconnect-frontend-container labconnect-frontend
          sleep 60
          docker logs labconnect-frontend-container
          docker stop labconnect-frontend-container
          docker rm labconnect-frontend-container
