name: Lint

on:
  pull_request:
    paths:
      - "src/**/*.js"
      - "src/**/*.jsx"
      - "src/**/*.ts"
      - "src/**/*.tsx"

permissions:
  contents: read

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Run EsLint
        uses: sibiraj-s/action-eslint@c24ff92cabb3ad38994c99f5583c59125ea040b0
        with:
          eslint-args: "src/**/*.{ts,tsx} --max-warnings=0"
          extensions: "ts,tsx"
          annotations: true
