name: Lint

on: [push, pull_request]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci --legacy-peer-deps
      - name: Run EsLint
        uses: sibiraj-s/action-eslint@v3
        with:
          eslint-args: "src/**/*.{js,jsx,ts,tsx} --max-warnings=0"
          extensions: "js,jsx,ts,tsx"
          annotations: true
